# ## get request
GET http://localhost:8000


### get single or all task from server
GET http://localhost:8000/api/v1/task/62675161d4f58e6cd390c401


### post task from server
POST http://localhost:8000/api/v1/task
Content-Type: application/json

{
    "task": "Coding",
    "hr": "18"
}


### delete task from server
DELETE http://localhost:8000/api/v1/task
